### ISSUE TITLE
This has recently started to fail to find the video on ITV.COM

### ISSUE THREAD

**Issue by broadstairs** [monsieurvideo/get-flash-videos#169]
Until recently I had been able to download vieos from ITV.COM here in the UK without any problem.I attach the debug output from a recent attempt. Is it possible to fix this please?
[itvtext.txt](https://github.com/monsieurvideo/get-flash-videos/files/32363/itvtext.txt)

**Comment by njtaylor** [comment]
On 11/11/15 22:10, broadstairs wrote:
> Until recently I had been able to download vieos from ITV.COM here in
> the UK without any problem.I attach the debug output from a recent
> attempt. Is it possible to fix this please?
> itvtext.txt
> <https://github.com/monsieurvideo/get-flash-videos/files/32363/itvtext.txt>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/monsieurvideo/get-flash-videos/issues/169>.
> 

I use a slightly different URL,

get_flash_videos
"http://www.itv.com/CatchUp/Video/default.html?ViewType=5&amp;Filter=354080"

Using method 'itv' plugin version 0.06 for
http://www.itv.com/CatchUp/Video/default.html?ViewType=5&amp;Filter=354080
Downloading
http://www.itv.com/CatchUp/Video/default.html?ViewType=5&amp;Filter=354080
RTMPDump v2.4-git-a107cef9 KSV-2015-05-05
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   duration                2770.00
INFO:   moovPosition            32.00
INFO:   width                   896.00
INFO:   height                  504.00
INFO:   videocodecid            avc1
INFO:   audiocodecid            mp4a
INFO:   avcprofile              100.00
INFO:   avclevel                31.00
INFO:   aacaot                  2.00
INFO:   videoframerate          25.00
INFO:   audiosamplerate         48000.00
INFO:   audiochannels           2.00
INFO: trackinfo:
INFO:   length                  69250.00
INFO:   timescale               25.00
INFO:   language                und
INFO: sampledescription:
INFO:   sampletype              avc1
INFO:   length                  132958208.00
INFO:   timescale               48000.00
INFO:   language                und
INFO: sampledescription:
INFO:   sampletype              mp4a
1-5634-0041-001_Lewis-What-Lies-Tangled-Part-2_PC011200_16X9.flv: 99%
(319346.80 / 321922.18 KiB)
Done. Saved 327894122 bytes to
1-5634-0041-001_Lewis-What-Lies-Tangled-Part-2_PC011200_16X9.flv

I use this myself for ITV programmes.

Your notice my plugin version is 0.06, your's is 0.04, there are already
some updates available


The url you used also worked for me.

$ get_flash_videos
"https://www.itv.com/itvplayer/lewis/series-9/episode-6-what-lies-tangled-part-2"

Using method 'itv' plugin version 0.06 for
https://www.itv.com/itvplayer/lewis/series-9/episode-6-what-lies-tangled-part-2
Downloading
https://www.itv.com/itvplayer/lewis/series-9/episode-6-what-lies-tangled-part-2
RTMPDump v2.4-git-a107cef9 KSV-2015-05-05
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   duration                2770.00
INFO:   moovPosition            32.00
INFO:   width                   896.00
INFO:   height                  504.00
INFO:   videocodecid            avc1
INFO:   audiocodecid            mp4a
INFO:   avcprofile              100.00
INFO:   avclevel                31.00
INFO:   aacaot                  2.00
INFO:   videoframerate          25.00
INFO:   audiosamplerate         48000.00
INFO:   audiochannels           2.00
INFO: trackinfo:
INFO:   length                  69250.00
INFO:   timescale               25.00
INFO:   language                und
INFO: sampledescription:
INFO:   sampletype              avc1
INFO:   length                  132958208.00
INFO:   timescale               48000.00
INFO:   language                und
INFO: sampledescription:
INFO:   sampletype              mp4a
1-5634-0041-001_Lewis-What-Lies-Tangled-Part-2_PC011800_16X9.flv: 0%
(4530.39 / 566299.00 KiB)^C


As you don't state which OS etc, there are a number of ways to update,

https://github.com/monsieurvideo/get-flash-videos/releases

Under releases, there are some downloads.
combined-get_flash_videos - most of the perl source in a single file.
get_flash_videos - single file with Sites included.
then 2 source archive files.

https://github.com/monsieurvideo/get-flash-videos/blob/master/lib/FlashVideo/Site/Itv.pm
Is the location of the Itv site, select raw and save as a file and place
into ~/get_flash_videos/plugins directory, (this should be removed if
you install an upto date version).

You can also update by using git.


Changes are in this commit if using git

commit 3abd6e715062ed656705a2f052a1588a969efe02
Author: Nigel Taylor <njtaylor0101@gmail.com>
Date:   Sat Jun 13 09:17:07 2015 +0100

    For some in the returned XML ITV has been change to PC01
    before the bitrate.

These is another commit after this for ITV.

**Comment by broadstairs** [comment]
Thanks for the update. I am running this on Fedora which installs it in a single directory. Replacing the itv.pm with the one from here does not work. I took a copy of the combined file and using that it works OK so this is resolved.
