### ISSUE TITLE
youtube download failing on NASA.gov channel

### ISSUE THREAD

**Issue by pcwalden** [monsieurvideo/get-flash-videos#196]
This youtube url from the NASA.gov channel is failing with a perl error.

https://www.youtube.com/watch?v=qWRJped5Tfw

Using method 'youtube' plugin version 0.02 for http://www.youtube.com/watch?v=qWRJped5Tfw
Downloading http://www.youtube.com/watch?v=qWRJped5Tfw
Use of uninitialized value in subroutine entry at /usr/share/perl5/URI/Escape.pm line 184.
Use of uninitialized value in subroutine entry at /usr/share/perl5/URI/Escape.pm line 184.
Unable to get YouTube video information.
Error: Unable to find video URL

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm the site is using Flash video and if you have Flash available
check that the URL really works(!).

Check for updates by running: /home/pwalden/bin/get_flash_videos-1.25 --update

If the latest version does not support this please open a bug

**Comment by karjonas** [comment]
I think the video is removed. Youtube says
"
This video has been removed by the user.
Sorry about that.
"

**Comment by pcwalden** [comment]
Yes you are correct. I should have checked the link :(

Sorry about this :)
