### ISSUE TITLE
Cannot download from tv4play.se

### ISSUE THREAD

**Issue by flyingzebras** [monsieurvideo/get-flash-videos#201]
get_flash_videos "http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452"
Using method 'tv4play' for http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452
Downloading http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452
Error: 
mismatched tag at line 6, column 2, byte 146 at /usr/lib/perl5/XML/Parser.pm line 187.
 (from FlashVideo::Site::Tv4play::/usr/share/perl5/FlashVideo/Site/Tv4play.pm::15)

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm the site is using Flash video and if you have Flash available
check that the URL really works(!).

Check for updates by running: /usr/bin/get_flash_videos --update

If the latest version does not support this please open a bug (or
contribute a patch!) at http://code.google.com/p/get-flash-videos/
make sure you include the output with --debug enabled.
Couldn't download any videos.

sudo /usr/bin/get_flash_videos --update
Unable to retrieve version data: 404 Not Found

**Comment by pcwalden** [comment]
This download worked for me. Are you using the latest on git?

$ get_flash_videos-1.25 'http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452'
Using method 'tv4play' plugin version 0.03 for http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452
Downloading http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452
Downloading segments
 12% [==========                                                                       ]^

**Comment by pcwalden** [comment]
@flyingzebras, if the latest git version is working for you, please close this issue.

**Comment by flyingzebras** [comment]
@pcwalden Give me a few days.

**Comment by davidhedlund** [comment]
@pcwalden As I also pointed out in this issue:
>sudo /usr/bin/get_flash_videos --update
>Unable to retrieve version data: 404 Not Found

Any ideas why I cannot update the package get-flash-videos this way?

**Comment by flyingzebras** [comment]
@pcwalden As I also pointed out in this issue:
>sudo /usr/bin/get_flash_videos --update
>Unable to retrieve version data: 404 Not Found

Any ideas why I cannot update the package get-flash-videos this way?

**Comment by flyingzebras** [comment]
https://github.com/monsieurvideo/get-flash-videos/issues/204

**Comment by pcwalden** [comment]
@flyingzebras 
>     sudo /usr/bin/get_flash_videos --update
>     Unable to retrieve version data: 404 Not Found
> 
> Is this a bug?

As @njtaylor explains in #204, the --update feature is no longer viable and needs to be removed. Also the documentation needs to be updated accordingly. Since we are all volunteering our work on get_flash_videos, someone needs to volunteer to do these things. If you would like to help improve this site's wiki or documentation, please give it a go.

You can download [the last release from here](https://github.com/monsieurvideo/get-flash-videos/releases).

Alternatively you can  use git to download the latest code and build your own.

Please close this issue as your original concerns have been directly resolved.

**Comment by flyingzebras** [comment]
@pcwalden tv4play.se require login to watch their Flash videos, do get_flash_videos login automatically? With the latest git version I get this:

get_flash_videos 'http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452'
Using method 'tv4play' for http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452
Downloading http://www.tv4play.se/program/unga-f%C3%B6r%C3%A4ldrar?video_id=3503452
Error: 
mismatched tag at line 6, column 2, byte 146 at /usr/lib/perl5/XML/Parser.pm line 187.
 (from FlashVideo::Site::Tv4play::/usr/share/perl5/FlashVideo/Site/Tv4play.pm::15)

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm the site is using Flash video and if you have Flash available
check that the URL really works(!).

Check for updates by running: /usr/bin/get_flash_videos --update

If the latest version does not support this please open a bug (or
contribute a patch!) at http://code.google.com/p/get-flash-videos/
make sure you include the output with --debug enabled.
Couldn't download any videos.

**Comment by karjonas** [comment]
@flyingzebras I believe you are still using the old version. It should say that you are using version 3 of the tv4play plugin. There is no support for logging in to the site so only non-premium videos are downloadable right now.

**Comment by pcwalden** [comment]
@karjonas
> There is no support for logging in to the site so only non-premium videos are downloadable right now.

Yes, that would be an enhancement. However, I would point out that get_flash_videos does have the infrastructure for users to define site login/passwords. See _man netrc_, for how to configure _~/.netrc_. The Pbs.pm plugin uses that mechanism to log into the pbs.org site and access higher definition video. However, I agree it is a significant amount of work to figure it out for a specific site.
