### ISSUE TITLE
How to use download from dplay?

### ISSUE THREAD

**Issue by flyingzebras** [monsieurvideo/get-flash-videos#202]
How do I download videos from say: http://www.dplay.se/gransbevakarna-australien/

The problem is that there are no links on the video images so there is no URL to copy.

**Comment by pcwalden** [comment]
Looks like the Dplay.pm site's plugin has not been refreshed since 2005. So it likely needs someone to update it to work with the current version of web site.

**Comment by flyingzebras** [comment]
@pcwalden 
>However, it looks like the Dplay.pm site's plugin has not been refreshed since 2005. So it likely needs someone to update it to work with the current version of web site.

Is it hard to update it for you?

**Comment by karjonas** [comment]
> How do I download videos from say: http://www.dplay.se/gransbevakarna-australien/
> 
> The problem is that there are no links on the video images so there is no URL to copy.

There are actually links if you press the titles. For instance http://www.dplay.se/gransbevakarna-australien/season-9-avsnitt-1/

**Comment by pcwalden** [comment]
@karjonas, I am glad the plugin works on the video links.

Sounds like the site plugin could be enhanced to find these video links and list them for the user to select.

**Comment by flyingzebras** [comment]
@karjonas You need a Flash player installed to make the links working. I do not have a Flash player on my system.

@karjonas Good call.

**Comment by flyingzebras** [comment]
@pcwalden Good call.

**Comment by karjonas** [comment]
@flyingzebras Yes, the links under "Senaste" do not work but the links under "Mer från Gränsbevakarna Australien" do. I suggest you use these until the script has been improved.

![ssdplay](https://cloud.githubusercontent.com/assets/754587/18614755/3b0e818a-7d95-11e6-988f-01cec810c319.png)

@pcwalden Yes, that would be better.

**Comment by flyingzebras** [comment]
@karjonas Sweet!

**Comment by flyingzebras** [comment]
@karjonas I get this with the latest git version:

get_flash_videos 'http://www.dplay.se/gransbevakarna-australien/season-9-avsnitt-1/'
Using method 'generic' for http://www.dplay.se/gransbevakarna-australien/season-9-avsnitt-1/
Downloading http://www.dplay.se/gransbevakarna-australien/season-9-avsnitt-1/
Guessed http://www.dplay.se/gransbevakarna-australien/season-9-avsnitt-1/%5C trying...
Guessed http://www.dplay.se/gransbevakarna-australien/season-9-avsnitt-1/DiscoverySBS_flash_live trying...
Using method 'generic' for http://www.googletagmanager.com/ns.html?id=GTM-TMK34L
Downloading http://www.googletagmanager.com/ns.html?id=GTM-TMK34L
Error: No URLs found at /usr/share/perl5/FlashVideo/Generic.pm line 144.

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm the site is using Flash video and if you have Flash available
check that the URL really works(!).

Check for updates by running: /usr/bin/get_flash_videos --update

If the latest version does not support this please open a bug (or
contribute a patch!) at http://code.google.com/p/get-flash-videos/
make sure you include the output with --debug enabled.
Couldn't download any videos.

**Comment by karjonas** [comment]
@flyingzebras Please verify you are running the right version by running
``` ./get_flash_videos --version ```

**Comment by flyingzebras** [comment]
@karjonas 
>./get_flash_videos --version
>Can't locate Module/Find.pm in @INC (you may need to install the Module::Find module) (@INC contains: /home/cryptonite/.local/share/Trash/files/get-flash-videos-master/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/cryptonite/.local/share/Trash/files/get-flash-videos-master/lib/FlashVideo/URLFinder.pm line 5.
BEGIN failed--compilation aborted at /home/cryptonite/.local/share/Trash/files/get-flash-videos-master/lib/FlashVideo/URLFinder.pm line 5.
Compilation failed in require at ./get_flash_videos line 40.
BEGIN failed--compilation aborted at ./get_flash_videos line 40.

>get_flash_videos --version
>get_flash_videos version  (http://code.google.com/p/get-flash-videos/)

**Comment by flyingzebras** [comment]
@karjonas This apply to https://github.com/monsieurvideo/get-flash-videos/archive/master.zip downloaded earlier today.

**Comment by flyingzebras** [comment]
@karjonas I'm not sure how to build get-flash-videos on Debian, https://github.com/monsieurvideo/get-flash-videos/wiki/Installation doesn't say much.

**Comment by flyingzebras** [comment]
https://code.google.com/archive/p/get-flash-videos/wikis/Installation.wiki says for:
>sudo apt-get install libwww-mechanize-perl libxml-simple-perl wget http://get-flash-videos.googlecode.com/files/get-flash-videos_1.24-1_all.deb sudo dpkg -i get-flash-videos_1.24-1_all.deb

But http://get-flash-videos.googlecode.com/files/get-flash-videos_1.24-1_all.deb don't exist.

**Comment by flyingzebras** [comment]
sudo apt-get install libwww-mechanize-perl libxml-simple-perl
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/get-flash-videos/get-flash-videos_1.24-1_all.deb
get_flash_videos --version
>get_flash_videos version 1.24 (http://code.google.com/p/get-flash-videos/)

**Comment by flyingzebras** [comment]
Works: https://github.com/monsieurvideo/get-flash-videos/issues/202#issuecomment-247764416

**Comment by miguelsat82** [comment]
How I can download from dplay.jp in windows 10?

**Comment by karjonas** [comment]
Sorry to say it but this project is basically dead now so I suggest using youtube-dl or something else.

**Comment by miguelsat82** [comment]
using youtube-dl is possible?

**Comment by karjonas** [comment]
Yes, https://github.com/blackjack4494/yt-dlc/blob/master/docs/supportedsites.md
