### ISSUE TITLE
Unable to download from ITV Hub today

### ISSUE THREAD

**Issue by broadstairs** [monsieurvideo/get-flash-videos#216]
Trying to download the first episode of the new series of Victoria I get
<./getflash2 https://www.itv.com/hub/victoria/2a4229a0009
Wed 30 Aug 18:02:34 BST 2017
Running get_flash_video2 now for https://www.itv.com/hub/victoria/2a4229a0009 
No plugins installed
Trying to open plugin ~/.get_flash_videos/plugins/Www.pm
Using method 'itv' plugin version 0.09 for https://www.itv.com/hub/victoria/2a4229a0009
Downloading https://www.itv.com/hub/victoria/2a4229a0009
-> GET https://www.itv.com/hub/victoria/2a4229a0009
<- 500 text/plain (391): UTF8 off, ASCII, 391 characters 391 bytes
Couldn't download 'https://www.itv.com/hub/victoria/2a4229a0009': 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
Production ID 

Error: No id (filter) found in URL or production id

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm that the URL is valid and that you are running the latest
version of get-flash-videos.

If the latest version does not support this site please create a bug
report at https://github.com/monsieurvideo/get-flash-videos making
sure you include the output with --debug enabled. Alternatively,                                                                                                          
fix it yourself and send us a pull request.                                                                                                                               
Couldn't download any videos.                                                                                                                                             
Wed 30 Aug 18:02:35 BST 2017                                                                                                                                              
Complete https://www.itv.com/hub/victoria/2a4229a0009   >

using combined-get_flash_videos-1.25.94

**Comment by njtaylor** [comment]
Looks to be missing Mozilla::CA, this can't be included as it adds a file with the certificate authorities, and the version used on OpenBSD is modified to point to a single CA file rather than duplicating many CA files, causing confusion. For other OS a Mozilla::CA needs to be installed, someone else had the same problem a while back, reply was.

> The handling of the SSL part is nothing to do with get_flash_videos
> itself, the certificates to trust come from the perl module Mozilla::CA
> or by setting an environment variable to the file with the trusted CA's.
>
> For OpenSUSE you need the package perl-Mozilla-CA
> If installed already and still a problem then it's the location of the
> ca file, or out of date ca file.

Debian the package is libmozilla-ca-perl

The name changes depending on the OS used. OpenBSD it's p5-Mozilla-CA.

I downloaded Victoria 2days ago, and tried again today and still works for me.

**Comment by broadstairs** [comment]
That has indeed solved the issue for me. Thanks.
