### ISSUE TITLE
Unable to install on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by broadstairs** [monsieurvideo/get-flash-videos#218]
I am trying to install the official openSUSE package  but get 

Problem: get-flash-videos-1.25.92-1.3.noarch requires perl(:MODULE_COMPAT_5.26.1), but this requirement cannot be provided

have you any ideas please? I have perl 5.26 installed.

**Comment by njtaylor** [comment]
A search shows MODULE_COMPAT_5_26.1 is related to the Perl version 5.26.1, but looks like get-flash-videos uses.

https://opensuse.pkgs.org/tumbleweed/opensuse-oss/get-flash-videos-1.25.92-1.3.noarch.rpm.html

This is to do with OpenSuse packaging, and specific to OpenSuse, some part of perl 5.26.1 is missing, this is a similar problem

https://forums.opensuse.org/showthread.php/511756-Problems-after-recent-software-udpate

From what I read it left old versions of OpenSuse that conflicted with the new. I don't use OpenSUSE.

**Comment by broadstairs** [comment]
I have now managed to get it working using the combined version from here on openSUSE Leap 42.3. The official version does install OK on that. Yes it looks like perl on Tumbleweed is rather a mess at present.

Stuart

**Comment by bear454** [comment]
@broadstairs: please file a bug, so we can get the issue resolved in Tumbleweed, https://bugzilla.opensuse.org/enter_bug.cgi?product=openSUSE%20Tumbleweed , or at least post to the forums.

**Comment by njtaylor** [comment]
I believe this has already been done here at least to a forum.

https://forums.opensuse.org/showthread.php/527648-Unable-to-install-package-missing-requisite

**Comment by broadstairs** [comment]
I have a thread open on openSUSE forums about this (as above). It seems that there have been issues after a scheduled outage on the openSUSE systems and so have agreed to wait a few days to see if it resolves itself. If not I shall indeed open a bug with them.
