### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by Stadly** [monsieurvideo/get-flash-videos#222]
If I run `.\get_flash_videos 'https://www.dplay.no/videoer/71-nord/sesong-19-episode-7'` in PowerShell, Windows asks me which program I would like to use to open the file. If I choose for example Notepad, the file `get_flash_videos` is opened in Notepad. What am I doing wrong?

**Comment by Stadly** [comment]
I just had to prepend `perl ` to the command. Maybe this should be added to the documentation?

**Comment by njtaylor** [comment]
Used to have instructions that said perl c:flash\get-flash-videos, google translate lost the correct mark-up in transferring the wiki pages.
